Repository anay-208/nextjs-hackathon, pull requests merged in 2025-04, with the labels that each got.

#11 Add drizzle setup
  .gitignore
  README.md
  components.json
  drizzle.config.ts
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/app/loading.tsx
  src/app/page.tsx
  src/db/index.ts
  src/db/schema.ts
  tsconfig.json
Labels: ready to merge

#12 10 add journalling resource table
  src/app/api/journal/crud.ts
  src/db/schema.ts
Labels: ready to merge

#32 Add journaling api routes
  package.json
  pnpm-lock.yaml
  src/app/(app)/dashboard/journal/[id]/data.ts
  src/app/(product)/page.tsx
  src/app/api/journal/[id]/route.ts
  src/app/api/journal/count/route.ts
  src/app/api/journal/crud.ts
  src/app/api/journal/route.ts
  src/app/layout.tsx
  src/db/schema.ts
Labels: ready to merge

#34 Fix incorrect journal count response
  src/app/api/journal/count/route.ts
Labels: ready to merge

#35 Add eslint config
  .eslintrc.json
  eslint.config.mjs
  postcss.config.mjs
Labels: frontend, backend, ready to merge

#3 Add auth
  README.md
  package.json
  pnpm-lock.yaml
  postcss.config.mjs
  src/app/(app)/auth/sign-in/page.client.tsx
  src/app/(app)/auth/sign-in/page.tsx
  src/app/(app)/auth/sign-up/page.client.tsx
  src/app/(app)/auth/sign-up/page.tsx
  src/app/api/auth/[...all]/route.ts
  src/auth/client.ts
  src/auth/index.ts
  src/db/index.ts
  src/db/schema.ts
Labels: backend

#42 Fix readme is unclear about how to create a db
  README.md
Labels: ready to merge

#45 Convert api routes to server actions for journaling
  package.json
  pnpm-lock.yaml
  src/app/(app)/dashboard/journal/[id]/data.ts
  src/app/(app)/dashboard/journal/[id]/sidebar.tsx
  src/app/(app)/dashboard/journal/[id]/tiptap.client.tsx
  src/app/(app)/dashboard/journal/card.tsx
  src/app/api/journal/actions.ts
  src/app/api/journal/db.ts
  src/app/api/journal/types.ts
  src/app/api/utils.ts
  src/db/schema.ts
  src/db/utils.ts
  src/lib/utils.ts
Labels: ready to merge

#58 Add eslint configurations
  .eslintrc.json
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/(app)/journal/pagination.tsx
  src/lib/utils.ts
Labels: ready to merge
